# -*- coding: utf-8 -*-
"""PROJECT HARWARD.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QEfb2e0HchM-YfpiOHY2hK9l5BR4QIB3

# Simplified
"""

import requests
import json
import pprint
API_KEY = "9eacbe0f-7c79-421b-a1cb-303d3d2d79fd"

url = "https://api.harvardartmuseums.org/classification"
link = "https://api.harvardartmuseums.org/object"

params = {
    "apikey":API_KEY,
    "size":100
}

response = requests.get(url, params)

class_data = response.json()

divisions_to_collect = []
for record in class_data['records']:
    if record['objectcount'] > 2500:
        divisions_to_collect.append(record['name'])

all_division_records = {}

for division_name in divisions_to_collect[0:5]:
    all_division_records[division_name] = []
    for i in range(1, 26):  # pages 1 to 25
        params = {
            "apikey": API_KEY,
            "size": 100,
            "page": i,
            "division": division_name
        }

        response = requests.get(link, params=params)
        data = response.json()
        if "records" in data:
            all_division_records[division_name].extend(data["records"])

print("Data collection complete for the following divisions:")
for div, records in all_division_records.items():
    print(f"- {div}: {len(records)} records collected")

all_md = {}
all_media = {}
all_colors = {}

for division_name, records in all_division_records.items():
    all_md[division_name] = []
    all_media[division_name] = []
    all_colors[division_name] = []

    for record in records:
        # Extract metadata
        all_md[division_name].append(dict(
            object_id = record.get('id'),
            title = record.get('title'),
            culture = record.get('culture'),
            period = record.get('period'),
            century = record.get('century'),
            medium = record.get('medium'),
            dimension = record.get('height'),
            description = record.get('description'),
            department = record.get('department'),
            classification = record.get('classification'),
            accessionyear = record.get('accessionyear'),
            accessionmethod = record.get('accessionmethod')
        ))

        # Extract media information
        all_media[division_name].append(dict(
            object_id = record.get('objectid'),
            imagecount = record.get('imagecount'),
            metacount = record.get('metacount'),
            colourcount = record.get('colourcount'),
            rank = record.get('rank'),
            datebegin = record.get('datebegin'),
            dateend = record.get('dateend')
        ))

        # Extract color details
        color_details = record.get('colors')
        if color_details:
            for color_item in color_details:
                all_colors[division_name].append(dict(
                    object_id = record.get('objectid'),
                    colour = color_item.get('colour'),
                    spectrum = color_item.get('spectrum'),
                    hue = color_item.get('hue'),
                    percent = color_item.get('percent'),
                    css3 = color_item.get('css3')
                ))

import pandas as pd
import sqlalchemy
from sqlalchemy import create_engine
!pip install pymysql

url = "mysql+pymysql://okrkj9Aqr6VZPb8.root:UkgRlt2NTpXZY999@gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/Harward_Project?ssl_ca=/etc/ssl/certs/ca-certificates.crt&ssl_verify_cert=true&ssl_verify_identity=true"

engine = create_engine(url)

Accessories_MD = pd.DataFrame(all_md["Accessories (non-art)"])
Accessories_Media = pd.DataFrame(all_media["Accessories (non-art)"])
Accessories_Colors = pd.DataFrame(all_colors["Accessories (non-art)"])

Photographs_MD = pd.DataFrame(all_md["Photographs"])
Photographs_Media = pd.DataFrame(all_media["Photographs"])
Photographs_Colors = pd.DataFrame(all_colors["Photographs"])

Drawing_MD = pd.DataFrame(all_md["Drawings"])
Drawing_Media = pd.DataFrame(all_media["Drawings"])
Drawing_colors = pd.DataFrame(all_colors["Drawings"])

Prints_MD = pd.DataFrame(all_md["Prints"])
Prints_Media = pd.DataFrame(all_media["Prints"])
Prints_Colors = pd.DataFrame(all_colors["Prints"])

Paintings_MD = pd.DataFrame(all_md["Paintings"])
Paintings_Media = pd.DataFrame(all_media["Paintings"])
Paintings_Colors = pd.DataFrame(all_colors["Paintings"])

Accessories_MD.to_sql('Accessories_MD', con=engine, if_exists='replace', index=False)
Accessories_Media.to_sql('Accessories_Media', con=engine, if_exists='replace', index=False)
Accessories_Colors.to_sql('Accessories_Colors', con=engine, if_exists='replace', index=False)

Photographs_MD.to_sql('Photographs_MD', con=engine, if_exists='replace', index=False)
Photographs_Media.to_sql('Photographs_Media', con=engine, if_exists='replace', index=False)
Photographs_Colors.to_sql('Photographs_Colors', con=engine, if_exists='replace', index=False)

Drawing_MD.to_sql('Drawing_MD', con=engine, if_exists='replace', index=False)
Drawing_Media.to_sql('Drawing_Media', con=engine, if_exists='replace', index=False)
Drawing_colors.to_sql('Drawing_colors', con=engine, if_exists='replace', index=False)

Prints_MD.to_sql('Prints_MD', con=engine, if_exists='replace', index=False)
Prints_Media.to_sql('Prints_Media', con=engine, if_exists='replace', index=False)
Prints_Colors.to_sql('Prints_Colors', con=engine, if_exists='replace', index=False)

Paintings_MD.to_sql('Paintings_MD', con=engine, if_exists='replace', index=False)
Paintings_Media.to_sql('Paintings_Media', con=engine, if_exists='replace', index=False)
Paintings_Colors.to_sql('Paintings_Colors', con=engine, if_exists='replace', index=False)

"""# SQL Queries"""

